/* [SC-BIBLE V26.0] Engine Core - Protected Build */
let currentChapter=1,currentSecIndex=0,observer=null,isMarkingMode=!1,selectedText="",isAutoScrolling=!1,isTestMode=!1;var recognition=null,isListening=!1;let currentAudio=null,currentPlayingBtn=null,audioSpeed=1.0;
const Storage={get:()=>JSON.parse(localStorage.getItem("my_marks")||"{}"),set:a=>localStorage.setItem("my_marks",JSON.stringify(a)),add:(a,b,c)=>{const d=Storage.get(),e=`${a}-${b}`;d[e]||(d[e]=[]),d[e].includes(c)||d[e].push(c),Storage.set(d)},remove:(a,b,c)=>{const d=Storage.get(),e=`${a}-${b}`;d[e]&&(d[e]=d[e].filter(a=>a!==c),0===d[e].length&&delete d[e],Storage.set(d))}};
function initTheme(){const a=localStorage.getItem("theme")||"light";document.documentElement.setAttribute("data-theme",a),updateThemeIcon(a)}
function updateThemeIcon(a){document.querySelectorAll(".opt-group .icon-btn").forEach(b=>{"테마"===b.title&&(b.innerText="dark"===a?"☀️":"🌙")})}
window.toggleTheme=function(){const a=document.documentElement,b=a.getAttribute("data-theme"),c="dark"===b?"light":"dark";a.setAttribute("data-theme",c),localStorage.setItem("theme",c),updateThemeIcon(c)};
const MSG_EDIT_MODE="\uD83D\uDD8D\uFE0F <b>\uB4DC\uB798\uADF8=\uC800\uC7A5 / \uD130\uCE58=\uC0AD\uC81C</b> <span style='font-size:0.85em; opacity:0.9; margin-left:5px;'>(종료: \u270F\uFE0F클릭)</span>";
window.toggleEditMode=function(){isMarkingMode=!isMarkingMode;const a=document.body,b=document.getElementById("editModeBtn"),c=document.getElementById("modeToast");isMarkingMode?(a.classList.remove("mode-memorize"),a.classList.add("mode-marking"),b.classList.add("editing"),document.querySelectorAll(".verse-card").forEach(a=>a.classList.remove("hidden")),c.innerHTML=MSG_EDIT_MODE,c.style.opacity=1,c.style.backgroundColor="rgba(33, 37, 41, 0.95)"):(a.classList.remove("mode-marking"),a.classList.add("mode-memorize"),b.classList.remove("editing"),window.getSelection().removeAllRanges(),document.getElementById("saveMarkBtn").style.display="none",document.getElementById("saveMarkBtn").innerText="\uD83D\uDD8D\uFE0F 선택 저장",document.getElementById("saveMarkBtn").style.background="",document.getElementById("masterBtn").style.display="flex",c.innerText="\uD83D\uDC46 암기 모드 (터치하여 확인)",setTimeout(()=>c.style.opacity=0,1500))};
function handleSelection(){if(!isMarkingMode)return;const a=window.getSelection(),b=a.toString().trim(),c=document.getElementById("saveMarkBtn"),d=document.getElementById("masterBtn");b.length>0&&a.anchorNode&&a.anchorNode.parentElement.closest(".verse-card")?(selectedText=b,c.style.display="flex",d.style.display="none"):(selectedText="",c.style.display="none",d.style.display="flex")}
window.saveMark=function(){if(!selectedText)return;const a=window.getSelection(),b=a.anchorNode.parentElement.closest(".verse-card");if(!b)return;const c=b.getAttribute("data-v-idx");if(null!==c){const d=window.scrollY;Storage.add(currentChapter,c,selectedText),load(currentChapter),window.scrollTo(0,d);const e=document.getElementById("saveMarkBtn"),f=document.getElementById("modeToast");e.innerHTML="\u2705 저장됨!",e.style.background="#00b894",f.innerHTML="\u2705 <b>저장 완료!</b>",f.style.backgroundColor="#00b894",setTimeout(()=>{isMarkingMode&&(e.style.display="none",e.innerText="\uD83D\uDD8D\uFE0F 선택 저장",e.style.background="",document.getElementById("masterBtn").style.display="flex",f.innerHTML=MSG_EDIT_MODE,f.style.backgroundColor="rgba(33, 37, 41, 0.95)"),selectedText="",a.removeAllRanges()},1e3)}};
window.deleteMark=function(a,b,c){isMarkingMode&&(event.stopPropagation(),confirm(`'${c}' 마킹을 삭제하시겠습니까?`)&&(Storage.remove(currentChapter,b,c),a=window.scrollY,load(currentChapter),window.scrollTo(0,a)))};
document.addEventListener("selectionchange",handleSelection);
window.load=function(a,b="top"){if("undefined"!=typeof isTestMode&&isTestMode&&toggleTestMode(),!db[a])return;currentChapter=a,document.querySelectorAll(".ch-btn").forEach((b,c)=>{if("number"==typeof a)b.classList.toggle("active",c+1===a);else b.classList.toggle("active","2월 시험"===b.innerText)});const c=document.getElementById("content"),d=document.getElementById("subNav");c.innerHTML="",d.innerHTML="";const e=Storage.get();db[a].sections.forEach((a,b)=>{const f=document.createElement("button");f.className="sub-btn",f.innerText=a.t,f.onclick=()=>{isAutoScrolling=!0,currentSecIndex=b,updateActiveButton(b),document.getElementById("s"+b).scrollIntoView({behavior:"smooth",block:"start"}),setTimeout(()=>isAutoScrolling=!1,800)},d.appendChild(f);const g=document.createElement("div");g.className="section-group",g.id="s"+b,g.innerHTML=`<div class="sec-header"><div class="sec-btn-group"><span class="pill-badge info">${a.r}</span><button class="pill-badge eye-btn" onclick="toggleAll(this)"><span>\uD83D\uDC41\uFE0F</span></button></div><span class="sec-title-text">${a.t}</span></div>`,a.v.forEach((b,d)=>{const f=document.createElement("div");f.className=isMarkingMode?"verse-card":"verse-card hidden",f.onclick=function(){isMarkingMode||(this.classList.toggle("hidden"),updateMasterButtonState())},f.setAttribute("data-v-idx",b.n);let h=b.t;const i=e[`${currentChapter}-${b.n}`];i&&i.length>0&&i.forEach(a=>{const c=new RegExp(`(${a})`,"g");h=h.replace(c,`<span class="user-mark" onclick="deleteMark(this, ${b.n}, '${a}')">$1</span>`)}),f.innerHTML=`<div class="v-num-wrapper"><div class="v-num">${b.n}</div><button class="speaker-btn" onclick="playBibleAudio(event, this, ${currentChapter}, '${b.n}')">\uD83D\uDD0A</button></div><div class="verse-text">${h}</div>`,g.appendChild(f)}),c.appendChild(g)}),observer&&observer.disconnect(),observer=new IntersectionObserver(a=>{isAutoScrolling||a.forEach(a=>{a.isIntersecting&&(currentSecIndex=parseInt(a.target.id.replace("s","")),document.querySelectorAll(".sub-btn").forEach((a,b)=>{a.classList.toggle("active-sub",b===currentSecIndex)}))})},{rootMargin:"-40% 0px -40% 0px"}),document.querySelectorAll(".section-group").forEach(a=>observer.observe(a)),"bottom"===b?(window.scrollTo(0,document.body.scrollHeight),currentSecIndex=db[a].sections.length-1):(window.scrollTo(0,0),currentSecIndex=0),updateMasterButtonState()};
window.moveSection=function(a){const b=document.querySelectorAll(".section-group");let c=currentSecIndex+a;isAutoScrolling=!0,c<0?"number"==typeof currentChapter&&currentChapter>1&&load(currentChapter-1,"bottom"):c>=b.length?"number"==typeof currentChapter&&currentChapter<22&&load(currentChapter+1,"top"):(currentSecIndex=c,b[c].scrollIntoView({behavior:"smooth",block:"start"}),updateActiveButton(c)),setTimeout(()=>isAutoScrolling=!1,800)};
function updateActiveButton(a){document.querySelectorAll(".sub-btn").forEach((b,c)=>{b.classList.toggle("active-sub",c===a),c===a&&isAutoScrolling&&b.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})})}
window.toggleAll=function(a){const b=a.closest(".section-group"),c=b.querySelectorAll(".verse-card");let d=Array.from(c).some(a=>a.classList.contains("hidden"));c.forEach(a=>a.classList.toggle("hidden",!d)),d?a.innerHTML="<span>\uD83D\uDE48</span>":a.innerHTML="<span>\uD83D\uDC41\uFE0F</span>",updateMasterButtonState()};
window.toggleChapter=function(){if(isMarkingMode)return;const a=document.querySelectorAll(".verse-card");let b=Array.from(a).some(a=>a.classList.contains("hidden"));a.forEach(a=>a.classList.toggle("hidden",!b)),document.querySelectorAll(".pill-badge.eye-btn").forEach(a=>{a.innerHTML=b?"<span>\uD83D\uDE48</span>":"<span>\uD83D\uDC41\uFE0F</span>"}),updateMasterButtonState()};
function updateMasterButtonState(){const a=document.querySelectorAll(".verse-card");if(0===a.length)return;const b=Array.from(a).some(a=>a.classList.contains("hidden")),c=document.getElementById("masterBtn"),d=c.querySelector(".pc-text"),e=c.querySelector(".mobile-text"),f="string"==typeof currentChapter?currentChapter:currentChapter+"장";b?(d.innerText=`\uD83D\uDC41\uFE0F ${f} 전체보기`,e.innerText=`\uD83D\uDC41\uFE0F 전체보기`):(d.innerText=`\uD83D\uDE48 ${f} 전체숨김`,e.innerText=`\uD83D\uDE48 전체숨김`)}
window.openSearch=function(){document.getElementById("searchModal").style.display="flex",setTimeout(()=>document.getElementById("searchInput").focus(),100)};
window.closeSearch=function(){document.getElementById("searchModal").style.display="none"};
window.doSearch=function(){const a=document.getElementById("searchInput").value.trim();if(!a)return;const b=a.replace(/\s+/g,""),c=document.getElementById("searchResults");c.innerHTML="";let d=0,e="";for(let f=1;f<=22;f++)db[f]&&db[f].sections.forEach((g,h)=>{g.v.forEach((g,i)=>{if(g.t.replace(/\s+/g,"").includes(b)){d++;const j=new RegExp(`(${a})`,"gi"),k=g.t.replace(j,'<span class="res-highlight">$1</span>');e+=`<div class="result-card" onclick="jumpToResult(${f},${h},${i})"><div class="res-info">계${f}:${g.n} (${sec.t})</div><div class="res-text">${k}</div></div>`}})});document.getElementById("searchStatusBox").style.display="block",document.getElementById("searchCount").innerHTML=`총 <b>${d}</b>건 검색 <span class="status-badge" style="margin-left:8px;">\uD83D\uDC46 클릭 시 해당 위치로 이동</span>`,c.innerHTML=e||'<div style="text-align:center;padding:20px;">결과 없음</div>'};
window.jumpToResult=function(a,b,c){closeSearch(),isMarkingMode=!1,document.body.classList.remove("mode-marking"),document.body.classList.add("mode-memorize"),document.getElementById("editModeBtn").classList.remove("active"),load(a),setTimeout(()=>{document.querySelectorAll(".verse-card").forEach(a=>a.classList.remove("hidden")),updateMasterButtonState();const d=document.getElementById("s"+b);if(d){const e=d.querySelectorAll(".verse-card")[c];e&&(e.scrollIntoView({behavior:"smooth",block:"center"}),e.classList.add("highlight-match"),setTimeout(()=>e.classList.remove("highlight-match"),2e3))}},100)};
window.toggleTestMode=function(){isTestMode=!isTestMode;const a=document.getElementById("testModeBtn"),b=document.querySelectorAll(".verse-card");if(0===b.length)return alert("\u26A0\uFE0F 먼저 장(Chapter)을 선택해주세요."),void(isTestMode=!isTestMode);if(isTestMode){a.innerHTML="\u274C",a.classList.add("active"),"undefined"!=typeof isMarkingMode&&isMarkingMode&&toggleEditMode(),b.forEach(a=>{a.classList.add("test-mode");const b=a.querySelector(".verse-text");if(!b)return;const c=b.innerText.trim();if(b.style.display="none",a.querySelector(".test-wrapper"))return;const d=document.createElement("div");d.className="test-wrapper",d.innerHTML=`<textarea class="test-input" placeholder="여기를 터치하여 입력하거나, [음성 입력]을 사용하세요."></textarea><div class="test-controls"><button type="button" class="v15-btn mic-btn" onclick="startStt(this)"><span>\uD83C\uDF99\uFE0F</span> 음성 입력</button><button type="button" class="v15-btn check-btn" onclick="gradeVerse(this, \`${escapeText(c)}\`)"><span>\uD83D\uDCAF</span> 채점 하기</button></div><div class="grade-result"></div>`,a.appendChild(d)})}else a.innerHTML="\uD83D\uDCDD",a.classList.remove("active"),isListening&&recognition&&(recognition.stop(),recognition=null,isListening=!1),document.querySelectorAll(".test-wrapper").forEach(a=>a.remove()),document.querySelectorAll(".verse-card").forEach(a=>a.classList.remove("test-mode")),document.querySelectorAll(".verse-text").forEach(a=>a.style.display="block")};
function escapeText(a){return a.replace(/`/g,"").replace(/"/g,"&quot;").replace(/\n/g," ")}
window.startStt=function(a){if(/Android|iPhone|iPad/i.test(navigator.userAgent)&&"file:"===location.protocol)return void alert("\u26D4 [보안 경고]\n모바일 '내 파일'에서는 마이크가 차단됩니다.\nHTTPS 주소로 접속해주세요.");const b=window.SpeechRecognition||window.webkitSpeechRecognition;if(!b)return void alert("이 브라우저는 음성 인식을 지원하지 않습니다.");const c=a.closest(".test-wrapper").querySelector(".test-input");if(isListening)return recognition&&(recognition.stop(),recognition=null),isListening=!1,a.classList.remove("listening"),void(a.innerHTML="<span>\uD83C\uDF99\uFE0F</span> 음성 입력");try{recognition=new b,recognition.lang="ko-KR",recognition.continuous=!0,recognition.interimResults=!1,recognition.onstart=function(){isListening=!0,a.classList.add("listening"),a.innerHTML="<span>\uD83D\uDED1</span> 마침"},recognition.onend=function(){isListening=!1,a.classList.remove("listening"),a.innerHTML="<span>\uD83C\uDF99\uFE0F</span> 음성 입력"},recognition.onresult=function(a){let b="";for(let c=a.resultIndex;c<a.results.length;++c)a.results[c].isFinal&&(b+=a.results[c][0].transcript+" ");c.value+=b,c.scrollTop=c.scrollHeight},recognition.onerror=function(b){console.error("Mic Error:",b.error),isListening&&(recognition.stop(),isListening=!1,a.classList.remove("listening"),a.innerHTML="<span>\uD83C\uDF99\uFE0F</span> 음성 입력"),"not-allowed"===b.error&&alert("마이크 권한을 허용해주세요.")},recognition.start()}catch(a){alert("마이크 실행 오류: "+a.message),isListening=!1}};
window.gradeVerse=function(a,b){const c=a.parentElement.parentElement,d=c.querySelector(".test-input").value.trim(),e=c.querySelector(".grade-result");if(!d)return void alert("내용을 입력해주세요!");const f=b.replace(/[.,?!'"\(\)\[\]]/g,"").replace(/\s+/g,""),g=d.replace(/[.,?!'"\(\)\[\]]/g,"").replace(/\s+/g,""),h=new diff_match_patch,i=h.diff_main(f,g);h.diff_cleanupSemantic(i);let j="",k=0,l=f.length;for(let a=0;a<i.length;a++){const[b,c]=i[a];if(0===b)j+=`<span class="diff-perfect">${c}</span>`;else if(-1===b){if(a+1<i.length&&1===i[a+1][0]){const b=i[a+1][1];c.length>=2&&b.length>=1&&c[0]===b[0]?(j+=`<span class="diff-particle">${b}</span>`,k+=.3*c.length):(j+=`<span class="diff-missing">[${c}]</span>`,j+=`<span class="diff-wrong">${b}</span>`,k+=c.length),a++}else j+=`<span class="diff-missing">[${c}]</span>`,k+=c.length}else 1===b&&(j+=`<span class="diff-wrong">${c}</span>`,k+=c.length)}let m=Math.max(0,Math.round((l-k)/l*100)),n=m>=90?"#00b894":m>=70?"#fdcb6e":"#ff7675";e.style.display="block",e.innerHTML=`<div style="background:${n}; color:#2d3436; display:inline-block; padding:6px 12px; border-radius:20px; font-weight:900; margin-bottom:10px; font-size:15px; box-shadow:0 2px 5px rgba(0,0,0,0.2);">점수: ${m}점</div><div style="margin-top:5px; word-break:break-all;">${j}</div>`};
(function(){"true"===sessionStorage.getItem("isLoggedIn")&&(document.getElementById("security-gate").style.display="none")})();
window.unlockGate=function(){const a=document.getElementById("gate-code"),b=document.getElementById("security-gate"),c=document.querySelector(".gate-card");"1440"===a.value?(sessionStorage.setItem("isLoggedIn","true"),b.style.opacity="0",b.style.visibility="hidden",setTimeout(()=>b.style.display="none",500)):(c.classList.add("gate-shake"),setTimeout(()=>c.classList.remove("gate-shake"),400),a.value="",a.focus())};
window.openDistrictLogin=function(){document.getElementById("districtModal").style.display="block",document.getElementById("dmPass").value="",document.getElementById("dmPass").focus()};
window.closeDistrictLogin=function(){document.getElementById("districtModal").style.display="none"};
window.checkDistrictLogin=function(){const a=document.getElementById("dmGroup").value,b=document.getElementById("dmPass").value,c={"장년회":"1001","부녀회":"2002","청년회":"3003","자문회":"4004","학생회":"5005","지역":"6006","24부서":"7007"};c[a]===b?(activateDistrictMode(a),closeDistrictLogin()):(alert("\u26D4 비밀번호가 일치하지 않습니다."),document.getElementById("dmPass").value="")};
window.activateDistrictMode=function(a){document.body.classList.add("mode-district");const b=`순천 ${a} 천국고시 준비자료`,c=`<svg xmlns='http://www.w3.org/2000/svg' width='300' height='300'><text x='50%' y='50%' dominant-baseline='middle' text-anchor='middle' transform='rotate(-45 150 150)' fill='%232c3e50' font-size='18' font-weight='bold' font-family='sans-serif'>${b}</text></svg>`,d="data:image/svg+xml;charset=utf-8,"+encodeURIComponent(c);document.querySelector(".watermark").style.backgroundImage=`url("${d}")`;const e=document.getElementById("chNav");e.innerHTML="";const f=document.createElement("button");f.className="ch-btn",f.innerText="\u2B05 나가기",f.onclick=function(){location.reload()},e.appendChild(f);const g=document.createElement("button");g.className="ch-btn active",g.innerText="2월 시험",g.onclick=function(){loadSpecialData()},e.appendChild(g),db.special=specialData["2월 시험"],load("special");const h=document.getElementById("modeToast");h.innerHTML=`\uD83D\uDC68\u200D\uD83C\uDF93 <b>구역장 모드 (${a})</b><br>환영합니다.`,h.style.opacity=1,setTimeout(()=>h.style.opacity=0,2e3)};
window.loadSpecialData=function(){load("special")};
let currentStep=0;
window.openManual=function(){const a=document.getElementById("manualOverlay");a.style.display="flex",setTimeout(()=>{a.classList.add("show"),a.style.opacity="1"},10),currentStep=0,renderStep()};
window.closeManual=function(){const a=document.getElementById("manualOverlay");a.classList.remove("show"),a.style.opacity="0",setTimeout(()=>{a.style.display="none"},300)};
window.renderStep=function(){const a=manualData[currentStep];document.getElementById("mStepBadge").innerText=`Step ${currentStep+1} / ${manualData.length}`,document.getElementById("mTitle").innerText=a.title,document.getElementById("mDesc").innerText=a.desc,document.getElementById("mVisualZone").innerHTML=`<div class="visual-item active">${a.html}</div>`;const b=document.querySelector(".btn-prev"),c=document.querySelector(".btn-next"),d=document.querySelector(".btn-start");b.style.visibility=0===currentStep?"hidden":"visible",currentStep===manualData.length-1?(c.style.display="none",d.style.display="block"):(c.style.display="block",d.style.display="none");const e=document.getElementById("mDots");e.innerHTML="",manualData.forEach((a,b)=>{const c=document.createElement("div");c.className="m-dot",b===currentStep&&c.classList.add("active"),e.appendChild(c)})};
window.nextStep=function(){currentStep<manualData.length-1&&(currentStep++,renderStep())};
window.prevStep=function(){currentStep>0&&(currentStep--,renderStep())};

/* --- [1호기 핵심 난독화 구역: Firebase Audio] --- */
window.toggleAudioPanel=function(){const a=document.getElementById("audio-popup-panel");a&&a.classList.toggle("show")};
window.setAudioSpeed=function(a,b){audioSpeed=parseFloat(a),currentAudio&&(currentAudio.playbackRate=audioSpeed),document.querySelectorAll(".spd-btn").forEach(a=>a.classList.remove("active")),b&&b.classList.add("active")};
window.playBibleAudio=function(a,b,c,d){a&&a.stopPropagation();const e=String(c).padStart(2,"0"),f=String(d).padStart(2,"0");
/* Base64 & Hex Obfuscation */
const _0x1a=atob("aHR0cHM6Ly9maXJlYmFzZXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vdjAvYi9zYy1iaWJsZS03YTA0Ni5maXJlYmFzZXN0b3JhZ2UuYXBwL28vcmV2JTJG");
const _0x2b="\x72\x65\x76\x5f",_0x3c="\x2e\x6d\x34\x61\x3f\x61\x6c\x74\x3d\x6d\x65\x64\x69\x61";
const g=`${_0x2b}${e}_${f}${_0x3c}`,h=`${_0x1a}${g}`;
if(currentAudio&&currentPlayingBtn===b)return currentAudio.pause(),currentAudio=null,currentPlayingBtn=null,b.innerText="\uD83D\uDD0A",void b.classList.remove("playing");currentAudio&&(currentAudio.pause(),currentPlayingBtn&&(currentPlayingBtn.innerText="\uD83D\uDD0A",currentPlayingBtn.classList.remove("playing"))),currentAudio=new Audio(h),currentAudio.playbackRate=audioSpeed,currentAudio.preservesPitch=!0,currentPlayingBtn=b,b.innerText="\u23F9\uFE0F",b.classList.add("playing"),currentAudio.play().catch(a=>{console.error("Audio Play Error:",a),alert("오디오 파일을 불러올 수 없습니다."),b.innerText="\uD83D\uDD0A",b.classList.remove("playing")}),currentAudio.onended=function(){b.innerText="\uD83D\uDD0A",b.classList.remove("playing"),currentAudio=null,currentPlayingBtn=null}};

window.addEventListener("load",function(){initTheme();const a=document.getElementById("chNav");for(let b=1;b<=22;b++){const c=document.createElement("button");c.className=`ch-btn ${1===b?"active":""}`,c.innerText=b+"장",c.onclick=()=>load(b),a.appendChild(c)}const b=document.querySelector(".opt-group");if(!document.getElementById("btnDistrictMode")&&b){const a=document.createElement("button");a.id="btnDistrictMode",a.className="icon-btn",a.innerHTML="\uD83D\uDC68\u200D\uD83C\uDF93",a.title="구역장 모드",a.onclick=()=>window.openDistrictLogin(),b.insertBefore(a,b.firstElementChild)}setTimeout(()=>load(1),100),document.body.addEventListener("touchstart",function(a){const b=a.target.closest("button");b&&(b.innerText.includes("저장")||b.innerText.includes("\uD83D\uDD8D"))&&(a.preventDefault(),b.click())},{passive:!1}),function(){document.documentElement.setAttribute("data-theme","light"),localStorage.setItem("theme","light")}(),"true"!==sessionStorage.getItem("isLoggedIn")&&setTimeout(()=>{const a=document.getElementById("gate-code");a&&a.focus()},500);const c=document.getElementById("gate-code");c&&c.addEventListener("keypress",function(a){"Enter"===a.key&&unlockGate()});const d=document.getElementById("mDots");d&&"undefined"!=typeof manualData&&manualData.forEach((a,b)=>{const c=document.createElement("div");c.className="m-dot",0===b&&c.classList.add("active"),d.appendChild(c)})});